import type { Metadata } from "next";
import { Kanit,Itim } from "next/font/google";
import "./globals.css";

const itim = Itim({
  subsets: ["thai"],
  weight: ["400"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${itim.className}`}
      >
        {children}

        <div className="text-center text-cyan-600 font-bold mt-95">
          <hr className="w-2xl mx-auto"/>
          Created by Worchai Homwanich
          <br />
          Copyright &copy; 2025
        </div>
      </body>
    </html>
  );
}
